### PR TITLE
Added ability to use MARCXML instead of MODS

### PR DESCRIPTION
**Pull request by egesu**
First check for MODS.xml file, if not exists check for MARCXML.xml

### CODE REVIEW

**Comment by MarcusBarnes** [comment]
@egesu Thank you. Would you have some test compound objects that use MARC XML rather than MODS XML so that I can test?

**Comment by egesu** [comment]
Sure, here:
[postcards.zip](https://github.com/MarcusBarnes/islandora_compound_batch/files/592380/postcards.zip)

**Comment by MarcusBarnes** [comment]
@egesu Tested and appears to work as expected.  Thank you for your contribution.

**Comment by egesu** [comment]
@MarcusBarnes thank you too for this great module, it saved me many hours :-)

**Pull request merged**
